#!/bin/bash

# Phase 4: Environment Configuration
# Generates .env files for backend and frontend

configure_environment() {
    print_step "Configuring environment files"
    
    local backend_env="$TEMP_DIR/iamgickpro/backend/.env.local"
    local frontend_env="$TEMP_DIR/iamgickpro/frontend/.env"
    
    # Generate backend .env.local file
    print_step "Creating backend environment configuration"
    
    cat > "$backend_env" << EOF
# Generated by IAMGickPro installer on $(date)

# Database Configuration
DATABASE_URL="mysql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?serverVersion=8.0&charset=utf8mb4"

# Application Environment
APP_ENV=prod
APP_SECRET=$(openssl rand -hex 32)
APP_DEBUG=0

# JWT Configuration
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=$(openssl rand -base64 32)

# Email Configuration
MAILER_DSN=smtp://localhost:587
MAIL_FROM_ADDRESS="$MAIL_FROM_ADDRESS"

# Application Configuration
APP_NAME="$APP_NAME"
FRONTEND_URL="$FRONTEND_URL"

# File Storage Configuration
UPLOAD_DIR=%kernel.project_dir%/public/uploads
MAX_UPLOAD_SIZE=50M

# Redis Configuration (for caching and sessions)
REDIS_URL=redis://localhost:6379

# Messenger Configuration (for async jobs)
MESSENGER_TRANSPORT_DSN=redis://localhost:6379/messages

# External Services
UNSPLASH_ACCESS_KEY="$UNSPLASH_API_KEY"
PEXELS_API_KEY="$PEXELS_API_KEY"

# Media Processing
IMAGEMAGICK_PATH=/usr/local/bin/convert
FFMPEG_PATH=/usr/local/bin/ffmpeg

# Security
CORS_ALLOW_ORIGIN="^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$|^$FRONTEND_URL$"
TRUSTED_PROXIES=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
TRUSTED_HOSTS="^(localhost|127\.0\.0\.1|$DOMAIN_NAME)$"

EOF

    print_success "Backend environment file created"
    
    # Generate frontend .env file  
    print_step "Creating frontend environment configuration"
    
    cat > "$frontend_env" << EOF
# Generated by IAMGickPro installer on $(date)

# API Configuration
VITE_API_URL=$FRONTEND_URL/api
VITE_APP_TITLE="$APP_NAME"
VITE_APP_SUBTITLE=Design Studio
VITE_PRO_PLAN_NAME=Pro

# Feature Flags
VITE_ENABLE_ANALYTICS=false
VITE_ENABLE_PLUGINS=true

# External Services
VITE_UNSPLASH_ACCESS_KEY="$UNSPLASH_API_KEY"
VITE_PEXELS_API_KEY="$PEXELS_API_KEY"

# Build Configuration
VITE_BUILD_SOURCEMAP=false
VITE_BUILD_MINIFY=true

EOF

    print_success "Frontend environment file created"
    
    # Validate environment files
    print_step "Validating environment configuration"
    
    if [[ ! -f "$backend_env" ]]; then
        print_error "Failed to create backend environment file"
        return 1
    fi
    
    if [[ ! -f "$frontend_env" ]]; then
        print_error "Failed to create frontend environment file"
        return 1
    fi
    
    print_success "Environment configuration completed"
}

# Run the configuration
configure_environment
